# Generated by Django 5.2.7 on 2025-10-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=254)),
                ('exercise_id', models.CharField()),
                ('exercise_name', models.CharField(max_length=254)),
                ('gif_url', models.URLField()),
                ('instructions', models.TextField()),
                ('target_muscles', models.TextField()),
                ('weight_str', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('weight_unit_str', models.CharField(blank=True, max_length=254, null=True)),
                ('sets_str', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('reps_str', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('time_car', models.TimeField(blank=True, null=True)),
                ('distance_car', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dist_unit_car', models.CharField(blank=True, max_length=254, null=True)),
                ('incline_car', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('speed_car', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('speed_unit_car', models.CharField(blank=True, max_length=254, null=True)),
                ('duration_mob', models.TimeField(blank=True, null=True)),
                ('sets_mob', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('reps_mob', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('intensity', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
