# Generated by Django 5.2.7 on 2025-10-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexercises',
            name='instructions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userexercises',
            name='target_muscles',
            field=models.JSONField(default=list),
        ),
    ]
