# Generated by Django 5.2.7 on 2025-10-28 21:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_exercises', '0002_alter_userexercises_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexercises',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
