# Generated by Django 5.2.7 on 2025-10-30 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_exercises', '0004_alter_userexercises_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexercises',
            old_name='user_email',
            new_name='user',
        ),
    ]
