# Generated by Django 5.2.7 on 2025-10-29 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_exercises', '0003_userexercises_date'),
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('weight_str', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('weight_unit_str', models.CharField(blank=True, max_length=254, null=True)),
                ('time_car', models.TimeField(blank=True, null=True)),
                ('distance_car', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dist_unit_car', models.CharField(blank=True, max_length=254, null=True)),
                ('incline_car', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('speed_car', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('speed_unit_car', models.CharField(blank=True, max_length=254, null=True)),
                ('duration_mob', models.TimeField(blank=True, null=True)),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
                ('user_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_exercises.userexercises')),
            ],
        ),
    ]
