# Generated by Django 5.2.7 on 2025-10-30 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_progress', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseprogress',
            old_name='user_email',
            new_name='user',
        ),
    ]
